config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers=>{ :registrations =>"user/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :friendships
  root "welcome#index"
  get 'my_portfolio', to: "users#my_portfolio"
  get "search_stock", to: "stocks#search"
  resources :user_stocks, only: [:create,:destroy]
  resources :users, only: [:show]
  get 'my_friends', to: "users#my_friends"
  get "search_friends", to: "users#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
   
   
   def self.find_by_ticker(ticker_symbol)
     where(ticker: ticker_symbol).first
   end
    
    
   def self.new_from_lookup(ticker_symbol)
     begin
       client = IEX::Api::Client.new(publishable_token: 'pk_516a9c50e70f4676a432483cf1a17181')
       looked_up_stock = client.quote(ticker_symbol)
       new(name: looked_up_stock.company_name,
           ticker: looked_up_stock.symbol, last_price: looked_up_stock.latest_price)
           rescue Exception => e
       return nil
     end
   end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end
  
  def under_stock_limit?
    (user_stocks.count < 10)
  end
  
  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def full_name
    return   "#{first_name} #{last_name}".strip if first_name || last_name
    "Anonymous"
  end


  def already_friends?(friend_id) 
    friend = friendships.find_by(friend_id: friend_id )
    return false unless friend
    friendships.where(friend_id: friend_id ).exists?
  end

  def self.search(keywords)
    keywords.strip!
    keywords.downcase!
    to_send_back = ((first_name_matches(keywords))+(last_name_matches(keywords))+(email_matches(keywords))).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(keywords)
    matches('first_name',keywords)
  end

  def self.last_name_matches(keywords)
    matches("last_name", keywords)
  end

  def self.email_matches(keywords)
    matches('email',keywords)
  end

  def self.matches(field_name,keywords)
    User.where("#{field_name} like ?","%#{keywords}%")
  end
  
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def destroy
		friendship = Friendship.find(params[:id])
		friendship.destroy
		flash[:warning] = "You are not  #{friendship.friend.full_name}'s friend any more."
		redirect_to my_friends_path
	end
	def create
		if Friendship.create(user_id:params[:user_id], friend_id: params[:friend_id])
			flash[:success] = "Friend is successfully added."
	      else
	        flash.now[:danger] = "Friends failed."
	      end
	      redirect_to my_friends_path
	end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def  search
    if params[:stock].blank?
        flash.now[:danger] = "Please enter a symbol."
    else
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:danger] = "Your symbol is invalid." unless @stock
    end  
    
    #render partial: 'users/search_result' #rails 4
    respond_to do |format|
       format.js { render partial: 'users/search_result' }
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
	before_action :configure_permitted_parameters

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
	end
	
	
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
      user = User.find(params[:user_id])
      stock = Stock.find_by_ticker(params[:stock_ticker])
      if !stock
        stock = Stock.new_from_lookup(params[:stock_ticker])
        stock.save
      end      
      if  UserStock.create(user: user,stock: stock)
        flash[:success] = "Stock is successfully added."
      else
        flash[:danger] = "Stock failed."
      end
      redirect_to my_portfolio_path
  end
  
  def destroy
    user_stock =  UserStock.find( params[:id])
    user_stock.destroy
    flash[:success] = "Stock #{user_stock.stock.name} is successfully removed."
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user_stocks = current_user.user_stocks
    @user = current_user
  end

  def my_friends
  	@friendships = current_user.friendships
  end

  def search  	
  	 if params[:keywords].blank?
        flash.now[:danger] = "Please enter a valid keyword to search."
    else
      @users= User.search(params[:keywords])
      flash.now[:danger] = "No such users." if @users.blank?
    end  
    
    #render partial: 'users/search_result' #rails 4
   respond_to do |format|
      format.js { render partial: 'users/users_result' }
    end
  end

  def show
    @user = User.find(params[:id])
    @user_stocks=@user.user_stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTrackerApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "FinanceTrackerApp", root_path, class: "navbar-brand"%> 
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-left">
             <% if current_user %>
                <li class="nav-item"><%= link_to "My Portfolios", my_portfolio_path , class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to "My Friends", my_friends_path , class: "nav-link" %></li>
                 <li class="nav-item"><%= link_to "My Profile",user_path(current_user),  class: "nav-link" %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
                <li class="nav-item "><a><i class="fa fa-user-circle" aria-hidden="true"></i>
                  <%= current_user.full_name.blank?? current_user.email : current_user.full_name %></li></a>
                <li class="nav-item"><%= link_to "log out",destroy_user_session_path(),  method: :delete,
                  class: "btn-danger btn-sm navbar-btn btn-color-white btn-background-red btn-logout" %></li>
            <% else %>
              <li class="nav-item"><%= link_to "login ",user_session_path , class: "btn nav-link  btn-sm btn-primary btn-color-white  btn-login" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container main-content">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              	<% if current_user %>
                  <li class="nav-item"><%= link_to "My Portfolios", my_portfolio_path, class: "nav-link"  %></li>
                  <li class="nav-item"><%= link_to "My Friends", my_friends_path , class: "nav-link" %></li>
                   <li class="nav-item"><%= link_to "Edit my profile",edit_registration_path(current_user),class: "nav-link" %></li>
              	<% else %>
              		<li><%= link_to "login ",user_session_path, class: "btn btn-sm btn-primary  btn-login" %></li>
             		<% end %>

            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->



    </div> <!-- /container -->
		<div class="container">
	      <footer>
        	<p>&copy; Company 2019</p>
      	  </footer>
  		</div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div >
	<table class="table table-stripped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Ticker</th>
				<th>Last Price</th>
				<% if @user && @user.id == current_user.id %><th>Actions</th><% end %>
			</tr>
		</thead>
		<tbody>
			<% @user_stocks.each do |user_stock|%>
				<tr>
					<td><%= user_stock.stock.name%></td>
					<td><%= user_stock.stock.ticker%></td>
					<td><%= user_stock.stock.last_price%></td>
					<% if @user && @user.id == current_user.id %>							
						<td>						
							<%= link_to "delete", user_stock_path(user_stock), method: :delete, class: 'btn btn-xs btn-danger'%>
						</td>						
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/_friends_look_up.html.erb
<div id="stock-lookup" class="row form-group">
	  <%= form_tag(search_friends_path, remote: true, method: :get,  id: "stock-lookup-form") do %>
	    <div class="form-group row no-padding text-center col-md-12">
	      <div class="col-md-8 ">
	        <%= text_field_tag :keywords, params[:keywords], 
	                                  placeholder: "Stock ticker symbol", autofocus: true,
	                                  class: "form-control search-box input-lg" %>
	      </div>
	      <div class="col-md-2">
	        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
	          <i class="fa fa-search"></i> Look up a friend
	        <% end %>
	      </div>
	    </div>
	  
	  <% end %>
	</div>

app/views/users/_list.html.erb
<div >
	<table class="table table-stripped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @friendships.each do |friendship|%>
				<tr>
					<td><%= friendship.friend.full_name%></td>
					<td><%= friendship.friend.email%></td>							
						<td>			
							<%= link_to "View Profile", user_path(friendship.friend), class: 'btn btn-xs btn-primary'%>			
							<%= link_to "delete", friendship_path(friendship), method: :delete, class: 'btn btn-xs btn-danger'%>
						</td>	
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/_search_result.html.erb
	<div class=" stock-results row form-group" >
		<div class=" no-padding  col-md-6">
		 	<% if params[:action]=='search'%>
		 		<%= bootstrap_flash %>
		 	<% end %>
		 	<% if @stock %>
				<div class="well  col-md-12">	
					<strong>Name: </strong><%= @stock.name %>		
					<strong>Ticker: </strong><%= @stock.ticker %>		
					<strong>Price: </strong><%= @stock.last_price %>
					<% if current_user.can_add_stock?(@stock.ticker) %>
						<%= link_to "Add to my stocks", user_stocks_path(user_id:current_user, stock_ticker: @stock.ticker), method: :post, class: "btn btn-xs btn-success"%>
					<% else %>
						<span class="label label-default">
							Stock cannot be added because you already have 
							<% if !current_user.under_stock_limit? %>
								10 stocks
							<% elsif current_user.stock_already_added?(@stock.ticker) %>
								this stock
							<% end %>
						</span>
					<% end %>
				</div>
			<% end %>
		</div>	
	</div>

app/views/users/_search_result.js.erb
$('#stock-results').html("<%= j (render 'users/search_result.html') %>")

app/views/users/_users_result.html.erb
	<div class=" users-results row form-group" >
		<div class=" no-padding  col-md-6">
		 	<% if params[:action]=='search'%>
		 		<%= bootstrap_flash %>
		 	<% end %>
		 	<% if @users %>
				<% @users.each do |user|%>
					<div class="well  col-md-12">	
						<strong>Name: </strong><%= user.full_name %>		
						<strong>Email: </strong><%= user.email%>		
						<% if !current_user.already_friends?(user.id) && current_user.id != user.id %>
							<%= link_to "Add to my friends", friendships_path(user_id:current_user, friend_id: user.id), method: :post, class: "btn btn-xs btn-success"%>
						<% else %>
							<span class="label label-default">
								You are already friends.								
							</span>
						<% end %>
					</div>
				<% end %>
			<% end %>
		</div>	
	</div>

app/views/users/_users_result.js.erb
$('#users-results').html("<%= j (render 'users/users_result.html') %>")

app/views/users/my_friends.html.erb
<h1>My Friends</h1>
<h3>Search for Friends</h3>
<div>
	<%= render 'users/friends_look_up'%>
	<div id="users-results">
		<%= render 'users/users_result'%>
	</div>
	<div id="my_users_listing">
		<%= render 'users/list'%>
	</div>
</div>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<h3>Search for Stocks</h3>
<div>
	<div id="stock-lookup" class="row form-group">
	  <%= form_tag(search_stock_path, remote: true, method: :get,  id: "stock-lookup-form") do %>
	    <div class="form-group row no-padding text-center col-md-12">
	      <div class="col-md-8 ">
	        <%= text_field_tag :stock, params[:stock], 
	                                  placeholder: "Stock ticker symbol", autofocus: true,
	                                  class: "form-control search-box input-lg" %>
	      </div>
	      <div class="col-md-2">
	        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
	          <i class="fa fa-search"></i> Look up a stock
	        <% end %>
	      </div>
	    </div>
	  
	  <% end %>
	</div>
	<div id="stock-results">
		<%= render 'users/search_result'%>
	</div>
	<div id="my_stock_listing">
		<%= render 'stocks/list'%>
	</div>
</div>

app/views/users/show.html.erb
<div class="well  col-md-12">	
	<center><h1>User Details</h1></center>
	<div class="col-md-12 ">
		<strong>Name: </strong><%= @user.full_name %>		<br/>
		<strong>Email: </strong><%= @user.email%>							
	</div>
	<div class="col-md-12 ">
		<% if @user_stocks.count > 0 %>
			<h2>List of tracked stocks</h2>
			<%= render 'stocks/list'%>
		<% else %>
			This user does not track any stocks
		<% end %>
	</div>
	<div class="col-md-12 ">
		<%= link_to "back", my_friends_path, class: "btn btn-primary btn-xs"%>
	</div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to the finance tracker app</h1>
<%= link_to "log out",destroy_user_session_path, method: :delete %>